// Mock industry-side data. Replace with GET /api/industry/* later.

export const partners = [
  "Himalaya Wellness",
  "Dabur",
  "Patanjali",
  "Zandu Ayurveda",
  "Kerala Ayurveda",
  "CCRAS",
  "NIA Jaipur",
  "AIIA New Delhi",
  "Baidyanath",
  "Charak Pharma",
];

export const industryPostings = [
  {
    id: "ip-1",
    title: "Herbal Formulation R&D Intern",
    type: "Internship",
    location: "Bengaluru, KA",
    stipend: 25000,
    deadline: "2026-10-12",
    status: "Active",
    applicants: 128,
    shortlisted: 14,
    skills: ["Herbal Formulation", "Quality Control & GMP"],
  },
  {
    id: "ip-2",
    title: "QA Documentation Associate",
    type: "Job",
    location: "Bengaluru, KA",
    stipend: 46000,
    deadline: "2026-09-29",
    status: "Active",
    applicants: 76,
    shortlisted: 9,
    skills: ["Quality Control & GMP", "Regulatory Affairs"],
  },
  {
    id: "ip-3",
    title: "Sustainable Sourcing Workshop",
    type: "Workshop",
    location: "Online",
    stipend: 0,
    deadline: "2026-09-18",
    status: "Closed",
    applicants: 240,
    shortlisted: 240,
    skills: ["Supply Chain"],
  },
];

export const applicantsByPosting = {
  "ip-1": [
    {
      id: "ap-a",
      name: "Ananya Sharma",
      initials: "AS",
      institution: "NIA Jaipur",
      match: 94,
      status: "Shortlisted",
      topSkills: ["Herbal Formulation", "Quality Control & GMP"],
      feedback: "Strong bench experience, schedule a technical round.",
    },
    {
      id: "ap-b",
      name: "Sneha Patil",
      initials: "SP",
      institution: "Govt. Ayurveda College, Pune",
      match: 91,
      status: "Selected",
      topSkills: ["Quality Control & GMP", "Lab Instrumentation"],
      feedback: "Offer released.",
    },
    {
      id: "ap-c",
      name: "Arjun Nair",
      initials: "AN",
      institution: "Amrita School of Ayurveda",
      match: 67,
      status: "Applied",
      topSkills: ["Herbal Formulation"],
      feedback: "",
    },
    {
      id: "ap-d",
      name: "Devansh Rao",
      initials: "DR",
      institution: "NIA Jaipur",
      match: 48,
      status: "Rejected",
      topSkills: ["Scientific Writing"],
      feedback: "Formulation exposure below role requirement.",
    },
  ],
  "ip-2": [
    {
      id: "ap-e",
      name: "Meghna Das",
      initials: "MD",
      institution: "NIH Kolkata",
      match: 86,
      status: "Shortlisted",
      topSkills: ["Data Analysis", "Regulatory Affairs"],
      feedback: "",
    },
    {
      id: "ap-f",
      name: "Imran Qureshi",
      initials: "IQ",
      institution: "AMU Aligarh",
      match: 59,
      status: "Applied",
      topSkills: ["Clinical Research"],
      feedback: "",
    },
  ],
  "ip-3": [
    {
      id: "ap-g",
      name: "Kavya Iyer",
      initials: "KI",
      institution: "SDM College of Naturopathy",
      match: 74,
      status: "Selected",
      topSkills: ["Yoga Therapy"],
      feedback: "Attended all modules.",
    },
  ],
};
