// Mock student directory + portfolio. Replace with GET /api/students later.

export const currentStudent = {
  id: "st-1",
  name: "Ananya Sharma",
  initials: "AS",
  headline: "BAMS Final Year · Aspiring Formulation Scientist",
  institution: "National Institute of Ayurveda, Jaipur",
  education: "BAMS, National Institute of Ayurveda (2022–2027)",
  location: "Jaipur, RJ",
  email: "ananya.sharma@example.in",
  profileCompletion: 78,
  bio: "Final-year BAMS student focused on herbal formulation and quality systems. I have run 14 bench-scale trials, love translating classical texts into reproducible processes, and am looking for an R&D internship in a GMP-certified unit.",
  skills: [
    { name: "Herbal Formulation", level: 86, verified: true },
    { name: "Quality Control & GMP", level: 74, verified: true },
    { name: "Panchakarma Practice", level: 70, verified: true },
    { name: "Scientific Writing", level: 66, verified: false },
    { name: "Data Analysis", level: 52, verified: false },
    { name: "Regulatory Affairs", level: 44, verified: false },
  ],
  certifications: [
    { id: "c1", name: "GMP Essentials for Manufacturing Units", issuer: "QCI", year: "2026" },
    { id: "c2", name: "Good Clinical Practice (GCP)", issuer: "NIDA", year: "2025" },
    { id: "c3", name: "Herbal Pharmacognosy Lab Methods", issuer: "CCRAS", year: "2025" },
  ],
  projects: [
    {
      id: "p1",
      name: "Stability profiling of a Triphala tablet",
      summary:
        "Six-month accelerated stability study comparing three binder systems; produced a recommended formulation with improved disintegration.",
      tags: ["Formulation", "QC"],
    },
    {
      id: "p2",
      name: "Digitised OPD outcome tracker",
      summary:
        "Built a spreadsheet-based outcome tracker used across 3 OPD units, covering 1,200+ patient visits.",
      tags: ["Data Analysis"],
    },
  ],
  achievements: [
    "Winner — National Startup Ideathon 2026 (state round)",
    "Best poster, National Ayurveda Research Conclave 2025",
    "NSS coordinator, 200+ community screening hours",
  ],
};

export const students = [
  {
    id: "st-1",
    name: "Ananya Sharma",
    initials: "AS",
    year: "Final",
    course: "BAMS",
    skillScore: 78,
    topSkill: "Herbal Formulation",
    placement: "Selected",
    company: "Dabur Research Foundation",
    mentor: "Dr. R. Venkatesan",
    applications: 4,
  },
  {
    id: "st-2",
    name: "Rohit Menon",
    initials: "RM",
    year: "Third",
    course: "BAMS",
    skillScore: 64,
    topSkill: "Panchakarma Practice",
    placement: "Shortlisted",
    company: "Kerala Ayurveda Ltd",
    mentor: "Dr. R. Venkatesan",
    applications: 6,
  },
  {
    id: "st-3",
    name: "Sneha Patil",
    initials: "SP",
    year: "Final",
    course: "B.Pharm (Ayurveda)",
    skillScore: 88,
    topSkill: "Quality Control & GMP",
    placement: "Selected",
    company: "Himalaya Wellness",
    mentor: "Dr. Meera Joshi",
    applications: 3,
  },
  {
    id: "st-4",
    name: "Imran Qureshi",
    initials: "IQ",
    year: "Second",
    course: "BUMS",
    skillScore: 51,
    topSkill: "Clinical Research",
    placement: "Applied",
    company: "—",
    mentor: "Dr. Meera Joshi",
    applications: 2,
  },
  {
    id: "st-5",
    name: "Kavya Iyer",
    initials: "KI",
    year: "Final",
    course: "BNYS",
    skillScore: 72,
    topSkill: "Yoga Therapy",
    placement: "Shortlisted",
    company: "Patanjali Wellness Institute",
    mentor: "Dr. R. Venkatesan",
    applications: 5,
  },
  {
    id: "st-6",
    name: "Devansh Rao",
    initials: "DR",
    year: "Third",
    course: "BAMS",
    skillScore: 45,
    topSkill: "Scientific Writing",
    placement: "Not started",
    company: "—",
    mentor: "Dr. Anil Kumar",
    applications: 0,
  },
  {
    id: "st-7",
    name: "Meghna Das",
    initials: "MD",
    year: "Final",
    course: "BHMS",
    skillScore: 81,
    topSkill: "Data Analysis",
    placement: "Selected",
    company: "National Institute of Ayurveda",
    mentor: "Dr. Anil Kumar",
    applications: 4,
  },
  {
    id: "st-8",
    name: "Arjun Nair",
    initials: "AN",
    year: "Second",
    course: "BAMS",
    skillScore: 58,
    topSkill: "Herbal Formulation",
    placement: "Applied",
    company: "—",
    mentor: "Dr. Meera Joshi",
    applications: 1,
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Sneha Patil",
    role: "QC Trainee → Analyst, Himalaya Wellness",
    initials: "SP",
    quote:
      "The skill assessment showed me exactly what a GMP unit expects. Three weeks after finishing my gap plan, I had an offer.",
  },
  {
    id: "t2",
    name: "Dr. R. Venkatesan",
    role: "Associate Professor, NIA Jaipur",
    initials: "RV",
    quote:
      "I can finally see where each of my students stands and match them with industry attachments that actually fit.",
  },
  {
    id: "t3",
    name: "Meghna Das",
    role: "Research Assistant, NIA",
    initials: "MD",
    quote:
      "Match percentages saved me weeks. I stopped applying blindly and started applying where I was genuinely strong.",
  },
];
