// Mock opportunity feed. Replace with GET /api/opportunities later.

export const opportunities = [
  {
    id: "op-1",
    title: "Herbal Formulation R&D Intern",
    org: "Himalaya Wellness",
    logo: "HW",
    type: "Internship",
    location: "Bengaluru, KA",
    mode: "On-site",
    stipend: 25000,
    duration: "6 months",
    deadline: "2026-10-12",
    match: 94,
    skills: ["Herbal Formulation", "Lab Instrumentation", "Quality Control & GMP"],
    audience: "student",
    applicants: 128,
    description:
      "Work alongside the formulation team on classical and proprietary Ayurvedic dosage forms. You will support batch trials, stability studies and documentation for new product development.",
    responsibilities: [
      "Assist bench-scale formulation trials for churna, kwatha and tablet forms",
      "Maintain batch manufacturing records and stability logs",
      "Support QC in raw-material identity and purity testing",
    ],
  },
  {
    id: "op-2",
    title: "Clinical Research Associate — Traditional Formulations Trials",
    org: "National Clinical Research Centre",
    logo: "AC",
    type: "Job",
    location: "New Delhi, DL",
    mode: "Hybrid",
    stipend: 52000,
    duration: "Full-time",
    deadline: "2026-09-30",
    match: 81,
    skills: ["Clinical Research", "Scientific Writing", "Data Analysis"],
    audience: "student",
    applicants: 64,
    description:
      "Coordinate multi-centre clinical studies evaluating classical formulations and interventions, from protocol drafting to site monitoring and data closure.",
    responsibilities: [
      "Draft protocols, ICFs and CRFs under investigator guidance",
      "Monitor sites for protocol and GCP compliance",
      "Prepare interim data summaries and study reports",
    ],
  },
  {
    id: "op-3",
    title: "Quality Control Analyst Trainee",
    org: "Dabur Research Foundation",
    logo: "DR",
    type: "Internship",
    location: "Ghaziabad, UP",
    mode: "On-site",
    stipend: 18000,
    duration: "4 months",
    deadline: "2026-10-05",
    match: 88,
    skills: ["Quality Control & GMP", "Lab Instrumentation"],
    audience: "student",
    applicants: 210,
    description:
      "Hands-on QC training across wet chemistry, chromatography and microbiology for herbal raw materials and finished goods.",
    responsibilities: [
      "Perform identity, purity and assay tests per pharmacopoeial methods",
      "Operate HPLC, UV-Vis and moisture analysers",
      "Document results in line with GLP practices",
    ],
  },
  {
    id: "op-4",
    title: "Yoga Therapy Programme Facilitator",
    org: "Patanjali Wellness Institute",
    logo: "PW",
    type: "Job",
    location: "Haridwar, UK",
    mode: "On-site",
    stipend: 38000,
    duration: "Full-time",
    deadline: "2026-11-02",
    match: 72,
    skills: ["Yoga Therapy", "Panchakarma Practice"],
    audience: "student",
    applicants: 47,
    description:
      "Design and deliver therapeutic yoga programmes for lifestyle-disorder cohorts within a residential wellness setting.",
    responsibilities: [
      "Assess participants and design graded therapy plans",
      "Run daily group and individual sessions",
      "Track outcomes and report programme effectiveness",
    ],
  },
  {
    id: "op-5",
    title: "Regulatory Affairs Workshop — Pharma & Herbal Exports",
    org: "Quality Council of India (QCI)",
    logo: "MA",
    type: "Workshop",
    location: "Online",
    mode: "Remote",
    stipend: 0,
    duration: "3 days",
    deadline: "2026-09-25",
    match: 69,
    skills: ["Regulatory Affairs", "Supply Chain"],
    audience: "student",
    applicants: 340,
    description:
      "A three-day intensive on export documentation, certification schemes and market-access requirements for herbal and wellness products.",
    responsibilities: [
      "Attend all three live modules",
      "Complete the case-study submission",
      "Sit the closing assessment for certification",
    ],
  },
  {
    id: "op-6",
    title: "Healthcare Data Analytics Intern",
    org: "National Institute of Ayurveda",
    logo: "NI",
    type: "Internship",
    location: "Jaipur, RJ",
    mode: "Hybrid",
    stipend: 20000,
    duration: "5 months",
    deadline: "2026-10-20",
    match: 63,
    skills: ["Data Analysis", "Scientific Writing"],
    audience: "student",
    applicants: 92,
    description:
      "Support the digital health cell in analysing OPD and programme datasets to surface insights for policy briefs.",
    responsibilities: [
      "Clean and structure programme datasets",
      "Build dashboards and summary visuals",
      "Co-author internal analytical notes",
    ],
  },
  {
    id: "op-7",
    title: "FDP: Modern Analytics for Healthcare & Science Faculty",
    org: "IIT Delhi × Research Council",
    logo: "ID",
    type: "FDP",
    location: "New Delhi, DL",
    mode: "Hybrid",
    stipend: 0,
    duration: "2 weeks",
    deadline: "2026-10-08",
    match: 91,
    skills: ["Data Analysis", "Scientific Writing", "Clinical Research"],
    audience: "faculty",
    applicants: 78,
    description:
      "A faculty development programme building analytical and research-design capability for educators, with a funded fellowship for participants.",
    responsibilities: [
      "Attend all sessions and lab practicals",
      "Submit a course-redesign artefact",
      "Mentor two students on an applied mini-project",
    ],
  },
  {
    id: "op-8",
    title: "Industrial Training Attachment — Manufacturing",
    org: "Zandu Formulations",
    logo: "ZA",
    type: "Industrial Training",
    location: "Vadodara, GJ",
    mode: "On-site",
    stipend: 30000,
    duration: "1 month",
    deadline: "2026-09-28",
    match: 84,
    skills: ["Quality Control & GMP", "Supply Chain"],
    audience: "faculty",
    applicants: 31,
    description:
      "Short industry attachment for faculty to observe commercial-scale manufacturing, QA systems and supply-chain operations.",
    responsibilities: [
      "Shadow production and QA teams across shifts",
      "Document a plant-to-classroom case study",
      "Present findings to the department",
    ],
  },
  {
    id: "op-9",
    title: "Collaborative Research Call — Standardisation of Polyherbals",
    org: "CCRAS",
    logo: "CC",
    type: "Research",
    location: "Pan-India",
    mode: "Hybrid",
    stipend: 0,
    duration: "18 months",
    deadline: "2026-11-15",
    match: 76,
    skills: ["Clinical Research", "Quality Control & GMP", "Scientific Writing"],
    audience: "faculty",
    applicants: 22,
    description:
      "Grant-supported call inviting academic principal investigators to partner with industry on marker-based standardisation of polyherbal formulations.",
    responsibilities: [
      "Submit a concept note with an industry partner",
      "Lead analytical work packages",
      "Publish and share protocols openly",
    ],
  },
  {
    id: "op-10",
    title: "Consultancy: Product Claim Substantiation",
    org: "Kerala Formulations Ltd",
    logo: "KA",
    type: "Consultancy",
    location: "Aluva, KL",
    mode: "Remote",
    stipend: 90000,
    duration: "3 months",
    deadline: "2026-10-18",
    match: 70,
    skills: ["Regulatory Affairs", "Clinical Research"],
    audience: "faculty",
    applicants: 14,
    description:
      "Advisory engagement to review evidence dossiers and design substantiation studies for three flagship products.",
    responsibilities: [
      "Audit existing evidence dossiers",
      "Recommend study designs and endpoints",
      "Deliver a substantiation roadmap",
    ],
  },
];

export const opportunityTypes = [
  "Internship",
  "Job",
  "Workshop",
  "FDP",
  "Industrial Training",
  "Research",
  "Consultancy",
];

export const locations = [
  "Bengaluru, KA",
  "New Delhi, DL",
  "Ghaziabad, UP",
  "Haridwar, UK",
  "Jaipur, RJ",
  "Vadodara, GJ",
  "Aluva, KL",
  "Online",
  "Pan-India",
];
