/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcademicianIndexRouteImport } from './routes/academician/index'
import { Route as AcademicianStudentsRouteImport } from './routes/academician/students'
import { Route as IndustryIndexRouteImport } from './routes/industry/index'
import { Route as IndustryApplicantsRouteImport } from './routes/industry/applicants'
import { Route as IndustryPostRouteImport } from './routes/industry/post'
import { Route as IndustryPostingsRouteImport } from './routes/industry/postings'
import { Route as InstitutionIndexRouteImport } from './routes/institution/index'
import { Route as InstitutionStudentsRouteImport } from './routes/institution/students'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentApplicationsRouteImport } from './routes/student/applications'
import { Route as StudentAssessmentRouteImport } from './routes/student/assessment'
import { Route as StudentPortfolioRouteImport } from './routes/student/portfolio'
import { Route as AcademicianOpportunitiesIndexRouteImport } from './routes/academician/opportunities/index'
import { Route as AcademicianOpportunitiesOpportunityIdRouteImport } from './routes/academician/opportunities/$opportunityId'
import { Route as StudentOpportunitiesIndexRouteImport } from './routes/student/opportunities/index'
import { Route as StudentOpportunitiesOpportunityIdRouteImport } from './routes/student/opportunities/$opportunityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicianIndexRoute = AcademicianIndexRouteImport.update({
  id: '/academician/',
  path: '/academician/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicianStudentsRoute = AcademicianStudentsRouteImport.update({
  id: '/academician/students',
  path: '/academician/students',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryIndexRoute = IndustryIndexRouteImport.update({
  id: '/industry/',
  path: '/industry/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryApplicantsRoute = IndustryApplicantsRouteImport.update({
  id: '/industry/applicants',
  path: '/industry/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPostRoute = IndustryPostRouteImport.update({
  id: '/industry/post',
  path: '/industry/post',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryPostingsRoute = IndustryPostingsRouteImport.update({
  id: '/industry/postings',
  path: '/industry/postings',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/institution/',
  path: '/institution/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionStudentsRoute = InstitutionStudentsRouteImport.update({
  id: '/institution/students',
  path: '/institution/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/student/applications',
  path: '/student/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssessmentRoute = StudentAssessmentRouteImport.update({
  id: '/student/assessment',
  path: '/student/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortfolioRoute = StudentPortfolioRouteImport.update({
  id: '/student/portfolio',
  path: '/student/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicianOpportunitiesIndexRoute =
  AcademicianOpportunitiesIndexRouteImport.update({
    id: '/academician/opportunities/',
    path: '/academician/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicianOpportunitiesOpportunityIdRoute =
  AcademicianOpportunitiesOpportunityIdRouteImport.update({
    id: '/academician/opportunities/$opportunityId',
    path: '/academician/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentOpportunitiesIndexRoute =
  StudentOpportunitiesIndexRouteImport.update({
    id: '/student/opportunities/',
    path: '/student/opportunities/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudentOpportunitiesOpportunityIdRoute =
  StudentOpportunitiesOpportunityIdRouteImport.update({
    id: '/student/opportunities/$opportunityId',
    path: '/student/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/academician/students': typeof AcademicianStudentsRoute
  '/industry/applicants': typeof IndustryApplicantsRoute
  '/industry/post': typeof IndustryPostRoute
  '/industry/postings': typeof IndustryPostingsRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessment': typeof StudentAssessmentRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/academician/': typeof AcademicianIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/student/': typeof StudentIndexRoute
  '/academician/opportunities/$opportunityId': typeof AcademicianOpportunitiesOpportunityIdRoute
  '/student/opportunities/$opportunityId': typeof StudentOpportunitiesOpportunityIdRoute
  '/academician/opportunities/': typeof AcademicianOpportunitiesIndexRoute
  '/student/opportunities/': typeof StudentOpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/academician/students': typeof AcademicianStudentsRoute
  '/industry/applicants': typeof IndustryApplicantsRoute
  '/industry/post': typeof IndustryPostRoute
  '/industry/postings': typeof IndustryPostingsRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessment': typeof StudentAssessmentRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/academician': typeof AcademicianIndexRoute
  '/industry': typeof IndustryIndexRoute
  '/institution': typeof InstitutionIndexRoute
  '/student': typeof StudentIndexRoute
  '/academician/opportunities/$opportunityId': typeof AcademicianOpportunitiesOpportunityIdRoute
  '/student/opportunities/$opportunityId': typeof StudentOpportunitiesOpportunityIdRoute
  '/academician/opportunities': typeof AcademicianOpportunitiesIndexRoute
  '/student/opportunities': typeof StudentOpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/academician/students': typeof AcademicianStudentsRoute
  '/industry/applicants': typeof IndustryApplicantsRoute
  '/industry/post': typeof IndustryPostRoute
  '/industry/postings': typeof IndustryPostingsRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/assessment': typeof StudentAssessmentRoute
  '/student/portfolio': typeof StudentPortfolioRoute
  '/academician/': typeof AcademicianIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/student/': typeof StudentIndexRoute
  '/academician/opportunities/$opportunityId': typeof AcademicianOpportunitiesOpportunityIdRoute
  '/student/opportunities/$opportunityId': typeof StudentOpportunitiesOpportunityIdRoute
  '/academician/opportunities/': typeof AcademicianOpportunitiesIndexRoute
  '/student/opportunities/': typeof StudentOpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/login'
    | '/academician/students'
    | '/industry/applicants'
    | '/industry/post'
    | '/industry/postings'
    | '/institution/students'
    | '/student/applications'
    | '/student/assessment'
    | '/student/portfolio'
    | '/academician/'
    | '/industry/'
    | '/institution/'
    | '/student/'
    | '/academician/opportunities/$opportunityId'
    | '/student/opportunities/$opportunityId'
    | '/academician/opportunities/'
    | '/student/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/login'
    | '/academician/students'
    | '/industry/applicants'
    | '/industry/post'
    | '/industry/postings'
    | '/institution/students'
    | '/student/applications'
    | '/student/assessment'
    | '/student/portfolio'
    | '/academician'
    | '/industry'
    | '/institution'
    | '/student'
    | '/academician/opportunities/$opportunityId'
    | '/student/opportunities/$opportunityId'
    | '/academician/opportunities'
    | '/student/opportunities'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/login'
    | '/academician/students'
    | '/industry/applicants'
    | '/industry/post'
    | '/industry/postings'
    | '/institution/students'
    | '/student/applications'
    | '/student/assessment'
    | '/student/portfolio'
    | '/academician/'
    | '/industry/'
    | '/institution/'
    | '/student/'
    | '/academician/opportunities/$opportunityId'
    | '/student/opportunities/$opportunityId'
    | '/academician/opportunities/'
    | '/student/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AcademicianStudentsRoute: typeof AcademicianStudentsRoute
  IndustryApplicantsRoute: typeof IndustryApplicantsRoute
  IndustryPostRoute: typeof IndustryPostRoute
  IndustryPostingsRoute: typeof IndustryPostingsRoute
  InstitutionStudentsRoute: typeof InstitutionStudentsRoute
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentAssessmentRoute: typeof StudentAssessmentRoute
  StudentPortfolioRoute: typeof StudentPortfolioRoute
  AcademicianIndexRoute: typeof AcademicianIndexRoute
  IndustryIndexRoute: typeof IndustryIndexRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  AcademicianOpportunitiesOpportunityIdRoute: typeof AcademicianOpportunitiesOpportunityIdRoute
  StudentOpportunitiesOpportunityIdRoute: typeof StudentOpportunitiesOpportunityIdRoute
  AcademicianOpportunitiesIndexRoute: typeof AcademicianOpportunitiesIndexRoute
  StudentOpportunitiesIndexRoute: typeof StudentOpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academician/': {
      id: '/academician/'
      path: '/academician'
      fullPath: '/academician/'
      preLoaderRoute: typeof AcademicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academician/students': {
      id: '/academician/students'
      path: '/academician/students'
      fullPath: '/academician/students'
      preLoaderRoute: typeof AcademicianStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/': {
      id: '/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof IndustryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/applicants': {
      id: '/industry/applicants'
      path: '/industry/applicants'
      fullPath: '/industry/applicants'
      preLoaderRoute: typeof IndustryApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/post': {
      id: '/industry/post'
      path: '/industry/post'
      fullPath: '/industry/post'
      preLoaderRoute: typeof IndustryPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/postings': {
      id: '/industry/postings'
      path: '/industry/postings'
      fullPath: '/industry/postings'
      preLoaderRoute: typeof IndustryPostingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/': {
      id: '/institution/'
      path: '/institution'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/students': {
      id: '/institution/students'
      path: '/institution/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof InstitutionStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/student/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assessment': {
      id: '/student/assessment'
      path: '/student/assessment'
      fullPath: '/student/assessment'
      preLoaderRoute: typeof StudentAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/portfolio': {
      id: '/student/portfolio'
      path: '/student/portfolio'
      fullPath: '/student/portfolio'
      preLoaderRoute: typeof StudentPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academician/opportunities/': {
      id: '/academician/opportunities/'
      path: '/academician/opportunities'
      fullPath: '/academician/opportunities/'
      preLoaderRoute: typeof AcademicianOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academician/opportunities/$opportunityId': {
      id: '/academician/opportunities/$opportunityId'
      path: '/academician/opportunities/$opportunityId'
      fullPath: '/academician/opportunities/$opportunityId'
      preLoaderRoute: typeof AcademicianOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/opportunities/': {
      id: '/student/opportunities/'
      path: '/student/opportunities'
      fullPath: '/student/opportunities/'
      preLoaderRoute: typeof StudentOpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/opportunities/$opportunityId': {
      id: '/student/opportunities/$opportunityId'
      path: '/student/opportunities/$opportunityId'
      fullPath: '/student/opportunities/$opportunityId'
      preLoaderRoute: typeof StudentOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AcademicianStudentsRoute: AcademicianStudentsRoute,
  IndustryApplicantsRoute: IndustryApplicantsRoute,
  IndustryPostRoute: IndustryPostRoute,
  IndustryPostingsRoute: IndustryPostingsRoute,
  InstitutionStudentsRoute: InstitutionStudentsRoute,
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentAssessmentRoute: StudentAssessmentRoute,
  StudentPortfolioRoute: StudentPortfolioRoute,
  AcademicianIndexRoute: AcademicianIndexRoute,
  IndustryIndexRoute: IndustryIndexRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  AcademicianOpportunitiesOpportunityIdRoute:
    AcademicianOpportunitiesOpportunityIdRoute,
  StudentOpportunitiesOpportunityIdRoute:
    StudentOpportunitiesOpportunityIdRoute,
  AcademicianOpportunitiesIndexRoute: AcademicianOpportunitiesIndexRoute,
  StudentOpportunitiesIndexRoute: StudentOpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
